services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://root:example@mongo:27017/mern-movies?authSource=admin
      - JWT_SECRET=devsecret
      - FRONTEND_ORIGIN=http://localhost:4173,http://localhost:5173
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: http://localhost:3000
    ports:
      - '4173:4173'
    depends_on:
      - backend

volumes:
  mongo-data:
