FROM node:20-alpine AS builder
WORKDIR /usr/src/app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /usr/src/app
RUN npm install -g serve

COPY --from=builder /usr/src/app/dist ./dist
EXPOSE 4173
CMD ["serve", "-s", "dist", "-l", "4173"]
