global:
  scrape_interval: 5s # Prometheus akan menarik data setiap 5 detik

scrape_configs:
  - job_name: 'movies-backend'
    static_configs:
      # Karena Prometheus jalan di Docker dan backend jalan di laptopmu,
      # kita gunakan 'host.docker.internal' untuk menembak ke localhost:3000
      - targets: ['host.docker.internal:3000']
